#!/bin/bash
# is the port we are looking for

if [ $# -lt 1 ]; then

  echo "Please provide a port number parameter for this script"
  echo "e.g. %content 1521"
  exit
  
fi

echo "It is owned by pid $(netstat -ltnp | grep -w :$1  |awk '{print $7}' |cut -d '/' -f 1)"