#!/bin/sh

if [ $1 \= "rm" ]; then
#	echo $1
#	echo $2
	t=`sed -n /$2/p /home/toto/scripts/todolist.txt`
#	echo "Delete task \""`sed -n /$2/p /home/sean/Documents/Misc/To\ Do\ List.txt`"\"? y/n"
#	echo $t	
	if [ "$t" != "" ]; then
		echo "Delete task \""$t"\"? y/n"
		read answer
		if [ $answer \= "y" ]; then
			sed -i /$2/d /home/toto/scripts/todolist.txt
			echo "Task deleted."
		else
			echo "Task not deleted."
		fi
	else
		echo "No task found with that name."
	fi
else
	echo "* "$* >> /home/toto/scripts/todolist.txt
	echo "Successfully added task \"$*\""
fi
